# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

target 'firebaseapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseapp

  target 'firebaseappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebaseapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseapp-tvOS

  target 'firebaseapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
